version: '3.8'

services:
  app:
    build: .
    container_name: lamp_laravel_app
    ports:
      - "8080:80"   # Apache
      - "2121:21"   # FTP (nếu cần)
    volumes:
      - .:/var/www/html
    restart: always